# Generated by Django 4.2.2 on 2023-06-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0005_citymodel_provincemodel_suburbmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerMax', models.CharField(blank=True, max_length=200, null=True)),
                ('powerrpm', models.CharField(blank=True, max_length=200, null=True)),
                ('torqueMax', models.CharField(blank=True, max_length=200, null=True)),
                ('torquerpm', models.CharField(blank=True, max_length=200, null=True)),
                ('engineSize', models.CharField(blank=True, max_length=200, null=True)),
                ('cylinders', models.CharField(blank=True, max_length=200, null=True)),
                ('charger', models.CharField(blank=True, max_length=200, null=True)),
                ('enginePosition', models.CharField(blank=True, max_length=200, null=True)),
                ('gearRatio', models.CharField(blank=True, max_length=200, null=True)),
                ('gearShift', models.CharField(blank=True, max_length=200, null=True)),
                ('drivenWheels', models.CharField(blank=True, max_length=200, null=True)),
                ('paddles', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='EconomyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.CharField(blank=True, max_length=200, null=True)),
                ('urban', models.CharField(blank=True, max_length=200, null=True)),
                ('extraUrban', models.CharField(blank=True, max_length=200, null=True)),
                ('co2', models.CharField(blank=True, max_length=200, null=True)),
                ('fuelRange', models.CharField(blank=True, max_length=200, null=True)),
                ('tankCapacity', models.CharField(blank=True, max_length=200, null=True)),
                ('autoStart', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_city', to='managers.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referance', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('kilometers', models.CharField(blank=True, max_length=200, null=True)),
                ('transmission', models.CharField(blank=True, max_length=200, null=True)),
                ('Fuel', models.CharField(blank=True, max_length=200, null=True)),
                ('seller', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('payment', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='managers.carvariantmodel')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='managers.categorymodel')),
                ('economy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_economy', to='vehicle.carenginemodel')),
                ('engine', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_engine', to='vehicle.carenginemodel')),
                ('features', models.ManyToManyField(blank=True, default=None, related_name='car_features', to='managers.carfeaturesmodel')),
                ('images', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='vehicle.carimagesmodel')),
                ('safety', models.ManyToManyField(blank=True, default=None, related_name='car_safety', to='managers.safetyfeaturesmodel')),
                ('sellerInfo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_info', to='vehicle.sellerinfomodel')),
            ],
        ),
    ]
