# Generated by Django 4.2.2 on 2023-06-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_alter_generalinfomodel_economy'),
        ('managers', '0005_citymodel_provincemodel_suburbmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('message', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='managers.provincemodel')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_car', to='vehicle.generalinfomodel')),
            ],
        ),
    ]
