# Generated by Django 4.2.2 on 2023-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequestmodel',
            name='openStatus',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
