# Generated by Django 4.2.2 on 2023-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_messagerequestmodel_openstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequestmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
